services:
  db:
    image: postgres:16
    container_name: retailmind-db
    shm_size: 1gb
    environment:
      POSTGRES_USER: retail
      POSTGRES_PASSWORD: retail
      POSTGRES_DB: retailmind
    ports:
      - "5433:5432"
    volumes:
      - retailmind_pgdata:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - shared_buffers=512MB
      - -c
      - work_mem=32MB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - max_wal_size=4GB
      - -c
      - random_page_cost=1.1
      - -c
      - track_io_timing=on
      - -c
      - shared_preload_libraries=pg_stat_statements

volumes:
  retailmind_pgdata:
